### ISSUE TITLE
Scout is not working on my ubuntu 13.10 / intel 64 built. 

### ISSUE THREAD

**Issue by johnerichumphries** [scoutapp/scout_realtime#21]
Installation went fine. The page loads, it detects the number of processors I have, and time tics by but it shows no information on usage or any other summary statistics / processes / or usage of any kind.

I have tried restarting as well as pausing and resuming with no avail.

**Comment by andre** [comment]
@johnerichumphries, mind posting the log? You'll find it in ~/.scout/scout_realtime.log

**Comment by johnerichumphries** [comment]
<pre>
Starting scout_realtime service...
I, [2014-03-11T15:35:58.519457 #10529]  INFO -- : starting web server 
I, [2014-03-11T15:35:58.519562 #10529]  INFO -- : starting stats collector thread
[2014-03-11 15:35:58] INFO  WEBrick 1.3.1
[2014-03-11 15:35:58] INFO  ruby 1.9.3 (2012-04-20) [x86_64-linux]
== Sinatra/1.4.4 has taken the stage on 5555 for production with backup from WEBrick
[2014-03-11 15:35:58] INFO  WEBrick::HTTPServer#start: pid=10529 port=5555
[2014-03-11 15:35:58] ERROR NoMethodError: undefined method `each_pair' for nil:NilClass
    /var/lib/gems/1.9.1/gems/server_metrics-1.2.1/lib/server_metrics/collectors/disk.rb:53:in `get_sizes'
localhost - - [11/Mar/2014:15:37:06 CDT] "GET / HTTP/1.1" 200 13060
- -> /
localhost - - [11/Mar/2014:15:37:06 CDT] "GET /stylesheets/styles.css?v=1.0 HTTP/1.1" 200 6481
http://localhost:5555/ -> /stylesheets/styles.css?v=1.0
localhost - - [11/Mar/2014:15:37:06 CDT] "GET /javascripts/jquery.debouncedresize.js HTTP/1.1" 200 1069
</pre>

**Comment by itsderek23** [comment]
Thanks for the debug output. 

It looks like the disk collector is having problems parsing the output of `df -Pkh`. Mind sharing that output?

**Comment by sgomez** [comment]
I solved this issue configuring LC_ALL and LANG to 'C' value:

```
bash$ LC_ALL=C LANG=C scout_realtime
```

I guess that _df_ is expecting data in English.

**Comment by itsderek23** [comment]
Thanks @sgomez. 

The Disk collector sets the `LANG` environment variable but not `LC_ALL`. I've [updated the Disk collector](https://github.com/scoutapp/server_metrics/commit/8e67b054887afa82d8a675be3e0274cef8bbac0d) to do this as well.

Mind trying the following:
- gem install server_metrics --pre (should install version 1.2.2.pre or later)
- scout_realtime stop
- scout_realtime start

**Comment by sgomez** [comment]
It works! Thanks.

**Comment by johnerichumphries** [comment]
Hi, 

Unfortunately, following sgomez's directions I installed server_metrics --pre, stopped and started the service, but still no luck. The program is behaving as it did before. Thanks again for all the feedback, and sorry for being slow to respond. It looks like a great tool!

@itsderek23 , here is my output from df -Pkh

xxx@mpk:~$  df -Pkh
Filesystem                             Size  Used Avail Use% Mounted on
/dev/sdb6                              687G  471G  182G  73% /
none                                   4.0K     0  4.0K   0% /sys/fs/cgroup
udev                                    30G   12K   30G   1% /dev
tmpfs                                  5.9G   62M  5.9G   2% /run
none                                   5.0M     0  5.0M   0% /run/lock
none                                    30G  5.4M   30G   1% /run/shm
none                                   100M   84K  100M   1% /run/user
/dev/sdb2                               95M   29M   67M  30% /boot/efi
/home/xxx/.Private                687G  471G  182G  73% /home/xxx
/dev/sr0                               1.3G  1.3G     0 100% /media/xxx/V1140
/dev/dm-0                              2.7T  1.1T  1.5T  43% /media/xxx/data
/dev/dm-1                              2.7T  2.1T  563G  79% /media/xxx/backup
/dev/dm-2                              3.6T  1.7T  1.8T  50% /media/xxx/backup2
acropolis.uchicago.edu:/home/xxx   37T   21T   16T  57% /home/xxx/remote/acropolis
/dev/sdf1                              3.6T  224G  3.2T   7% /server
/dev/sdg1                              1.9T   14G  1.9T   1% /media/xxx/My Passport
athensx.uchicago.edu:/share/klmweb      33T   20T   14T  61% /home/xxx/remote/klmweb
/dev/sda1                              230G  4.4G  214G   2% /media/xxx/ssh

**Comment by itsderek23** [comment]
Thanks @johnerichumphries. Looks like this isn't a language issue for you. 

We'll dig through this.

**Comment by itsderek23** [comment]
Sorry @johnerichumphries - need output from one other command: `mount`. Mind sharing?

**Comment by johnerichumphries** [comment]
here is the output:

xxx@mpk:~$ mount
/dev/sdb6 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
none on /sys/firmware/efi/efivars type efivarfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs
(rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
/dev/sdb2 on /boot/efi type vfat (rw)
systemd on /sys/fs/cgroup/systemd type cgroup
(rw,noexec,nosuid,nodev,none,name=systemd)
/home/xxx/.Private on /home/xxx type ecryptfs
(ecryptfs_check_dev_ruid,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs,ecryptfs_sig=eb57876551adc2c7,ecryptfs_fnek_sig=9f810bdea10e9096)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse
(rw,nosuid,nodev,user=xxx)
/dev/sr0 on /media/xxx/V1140 type udf
(ro,nosuid,nodev,uid=1000,gid=1000,iocharset=utf8,umask=0077,uhelper=udisks2)
/dev/mapper/luks-f6604150-b241-499a-b7fd-10d1e22345022 on /media/xxx/data
type ext4 (rw,nosuid,nodev,uhelper=udisks2)
/dev/mapper/luks-8491141d-32ca-43d7-bd9c-0085e959262a on /media/xxx/backup
type ext4 (rw,nosuid,nodev,uhelper=udisks2)
/dev/mapper/luks-08d55234-9905-4d71-b5f3-317cx234tac7 on /media/xxx/backup2
type ext4 (rw,nosuid,nodev,uhelper=udisks2)

On Wed, Mar 12, 2014 at 2:32 PM, Derek Haynes notifications@github.comwrote:

> Sorry @johnerichumphries https://github.com/johnerichumphries - need
> output from one other command: mount. Mind sharing?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scoutapp/scout_realtime/issues/21#issuecomment-37453549
> .

## 

John Eric Humphries

---

University of Chicago
Department of Economics
phone: 773.980.6575
email:  johneric@uchicago.edu

## web:    home.uchicago.edu/johneric

**Comment by itsderek23** [comment]
If English isn't the default language on your server, we've released an update to fix the disk metric parsing (scout_realitme -v1.0.2):

<pre>
gem install scout_realtime
scout_realtime stop
scout_realtime start
</pre>

**Comment by johnerichumphries** [comment]
Thanks @itsderek23,

Did this, and unfortunately it does not solve the problem.

**Comment by jbleuzen** [comment]
Same problem for me running on debian 7 with ruby 1.9.3p327.
The version 1.0.2 of scout_realtime didn't solve the problem.

I still have the line in scout_realtime.log : 

```
[2014-03-13 06:01:40] ERROR NoMethodError: undefined method `each_pair' for nil:NilClass
        /usr/local/rvm/gems/ruby-1.9.3-p194/gems/server_metrics-1.2.2/lib/server_metrics/collectors/disk.rb:55:in `get_sizes'
```

And here is my df output : 

```
❯ /home/johan   df -Pkh                                                                                                                                         6:02:16
Filesystem                     Size  Used Avail Use% Mounted on
/dev/sda1                       57G   12G   42G  23% /
udev                            10M     0   10M   0% /dev
tmpfs                          404M  328K  404M   1% /run
tmpfs                          5.0M     0  5.0M   0% /run/lock
tmpfs                          1.3G  4.0K  1.3G   1% /run/shm
/dev/sdb1                      230G   16G  203G   8% /media/data
X.X.X.X:/nas                   2.7T  1.3T  1.5T  48% /media/nas
```

EDIT :
Found the problem. In my `/etc/fstab` my disks are defined by UUID and when looking at the mount return I get the following output : 

```
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=214002,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=413608k,mode=755)
/dev/disk/by-uuid/53a9cc73-c09a-4597-bb9a-b5b4a22e0898 on / type ext3 (rw,relatime,errors=remount-ro,barrier=1,data=ordered)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1343100k)
/dev/sdb1 on /media/data type ext3 (rw,relatime,errors=remount-ro,user_xattr,acl,barrier=1,data=ordered)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
X.X.X.X:/nas on /media/nas type nfs4 (rw,relatime,vers=4,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=X.X.X.X,minorversion=0,local_lock=none,addr=X.X.X.X)
```

There is no matching between the UUID and /dev/sda1 which cause the error in server_metrics...

**Comment by itsderek23** [comment]
Thanks @jbleuzen. 

@johnerichumphries - I tested out your output and you have a similar issue with the mapped volumes as the devices in `mount` aren't under the same key in `df`.

Mind sharing your `cat /proc/diskstats` output?

**Comment by johnerichumphries** [comment]
Here you go:

xxx@mpk:~$ cat /proc/diskstats
   1       0 ram0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 17352 14705 3743934 6940 8852 502 8928468 5085672 0 43192
5092592
   8       1 sda1 17323 14675 3743462 6936 8851 502 8928468 5085648 0 43164
5092564
   8      16 sdb 59971502 83730 12876548623 37650588 11400650 7745181
1441709002 267420300 0 34732416 305040444
   8      17 sdb1 753 3609 34896 496 0 0 0 0 0 484 496
   8      18 sdb2 672 3741 7689 612 3 0 10 12 0 448 624
   8      19 sdb3 839 2697 28288 368 0 0 0 0 0 368 368
   8      20 sdb4 887 17535 39076 396 0 0 0 0 0 388 396
   8      21 sdb5 839 2697 28288 448 0 0 0 0 0 448 448
   8      22 sdb6 59966678 50472 12876379882 37647800 11208391 7745181
1441708992 267111392 0 34462688 304728936
  11       0 sr0 47 11 280 4088 0 0 0 0 0 4088 4088
   8      32 sdc 16667085 25859 2602505593 189464108 17056478 6985803
383913408 249365332 0 162514688 438821352
   8      33 sdc1 16667040 25853 2602505185 189463876 16941843 6985803
383913408 237147424 0 158029748 426603256
   8      48 sdd 70166 892 30170977 298832 250134 2850 230389392 84852632 0
1256140 85151264
   8      49 sdd1 70121 886 30170569 298732 248494 2850 230389392 84805876
0 1242188 85104408
   8      64 sde 40300952 24542 8304323463 94368576 40191524 74220387
3915192264 2982517012 147 256777348 3084662048
   8      80 sdf 1292220 12547 318347145 3826192 5953793 4288144 1195240072
706039640 0 158996352 709861212
   8      81 sdf1 1292175 12541 318346737 3826084 5953752 4288144
1195240072 706031792 0 158995996 709853300
 252       0 dm-0 16692832 0 2602502656 200427000 23928110 0 383913408
1948276328 0 164918324 2148685656
 252       1 dm-1 70492 0 30168040 359776 251339 0 230389392 135008984 0
1280056 135368776
 252       2 dm-2 40325814 0 8304322722 110292212 114520028 0 3915242560
1220966132 6288 259096008 1502637276
   8      96 sdg 101249 1620173 12932328 167456 31 261 2336 1688 0 81544
169140
   8      97 sdg1 101097 1620173 12931112 167384 31 261 2336 1688 0 81472
169060

On Thu, Mar 13, 2014 at 6:16 PM, Derek Haynes notifications@github.comwrote:

> Thanks @jbleuzen https://github.com/jbleuzen.
> 
> @johnerichumphries https://github.com/johnerichumphries - I tested out
> your output and you have a similar issue with the mapped volumes as the
> devices in mount aren't under the same key in df.
> 
> Mind sharing your cat /proc/diskstats output?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scoutapp/scout_realtime/issues/21#issuecomment-37598802
> .

## 

John Eric Humphries

---

University of Chicago
Department of Economics
phone: 773.980.6575
email:  johneric@uchicago.edu

## web:    home.uchicago.edu/johneric

**Comment by itsderek23** [comment]
We've released an attempted fix - there are cases when we can't map the `mount` output to the devices listed in `df -h`. When that happens, this skips over the `df` output vs. raising an exception.

To try:
- `gem install server_metrics -v1.2.3.pre`
- `scout_realtime stop`
- `scout_realtime start`

**Comment by johnerichumphries** [comment]
This now works!

I still don't get disk-utilization or network traffic, but everything else
appears to be working correctly.

Thanks.

On Fri, Mar 14, 2014 at 1:37 PM, Derek Haynes notifications@github.comwrote:

> We've released an attempted fix - there are cases when we can't map the
> mount output to the devices listed in df -h. When that happens, this
> skips over the df output vs. raising an exception.
> 
> To try:
> - gem install server_metrics -v1.2.3.pre
> - scout_realtime stop
> - scout_realtime start
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scoutapp/scout_realtime/issues/21#issuecomment-37681234
> .

## 

John Eric Humphries

---

University of Chicago
Department of Economics
phone: 773.980.6575
email:  johneric@uchicago.edu

## web:    home.uchicago.edu/johneric

**Comment by itsderek23** [comment]
> This now works!

Cool - moving in the right direction.

For disk utilization - it seems like I'm seeing data locally for your output. Mind trying the following:
- open the developer console in your browser
- type `metrics.disk`
- send us the output for the first disk. for example:

<pre>
/dev/xvda1: Object
avail: 4403.2
average_queue_length: 0
filesystem: "/dev/xvda1"
mounted_on : "/↵"
rps: 0
rps_kb: 0
size: 10137.6
used: 5324.8
used_percent: "55%"
utilization: 0
wps: 0
wps_kb: 0
</pre>

> network traffic

Mind adding your `cat /proc/net/dev` output to #10?

**Comment by jbleuzen** [comment]
Problem solved for me...
Thanks !
